name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  coverage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Use Node.js 16.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - run: npm ci
      - run: npm install nyc --no-save
      - run: npm run test -- --coverage
      - run: npx nyc report --reporter=text-lcov | npx coveralls
